################################### English language #####################################
[en]
languageName = "En"
languageCode = "en-us"
contentDir = "content/english"
weight = 1
[en.params]
footer_content = "Affordable SEO services. Everything you need to get started in SEO."
# copyright
copyright = "Copyright 2024"



################################### French language #####################################
[fr]
languageName = "Fr"
languageCode = "fr-fr"
contentDir = "content/french"
weight = 2
[fr.params]
footer_content = "Lorem ipsum dolor sit amet, consetetur sadipscing elitr, sed diam nonumy eirmod tempor invidunt ut labore dolore magna aliquyam eratnonumy onsetetur"
# copyright
copyright = "Copyright by your company"